#!/bin/bash
BASE_URL="https://raw.githubusercontent.com/github/gitignore/master"

if [ -z "$1" ];
  then
    printf "\n"
    echo "Gitignore Downloader"
    echo "===================="
    echo "Thanks to github/gitignore"
    printf "\n"
    echo "Usage:"
    echo "    $0 -<lang_abbr> or --<lang_name> to download .gitignore"
    echo "    specific to a language of your choise"
    printf "\n"
    echo "    Example: $0 -py downloads .gitignore for Python"
  else
    case "$1" in
      -py | --python)
        printf "\n"
        echo "Python"
        echo "$BASE_URL/Python.gitignore"
        curl --url "$BASE_URL/Python.gitignore" >> .gitignore
      ;;

      -js | --nodejs)
        printf "\n"
        echo "Nodejs"
      ;;

      *)
        printf "\n"
        echo "Error: program doesn't know the language you've provided"
      ;;
    esac
fi
